# vim:ft=ansible:
---
- name: Setup home assistant user
  become: yes
  user:
   name: "{{ home_assistant_user }}"
   system: yes
   state: present

- name: Setup directory for home assistant
  become: yes
  file:
    path: '/home/{{ home_assistant_user }}/{{ home_assistant_dir }}'
    state: directory
    owner: '{{ home_assistant_user }}'
    group: '{{ home_assistant_user }}'
